/*
 *  todo:本套教程QQ交流群：324702418
 *  todo: 代码在线地址：https://gitee.com/mayuanwei
 *
 * */

// 变量声明
// let pome
// pome = '劝君莫惜金缕衣 劝君惜取少年时'

// 变量初始化
let pome = '劝君莫惜金缕衣 劝君惜取少年时'




// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello World'
//
//   build() {
//     Row() {
//       Column() {
//         Text(this.message)
//           .fontSize(50)
//           .fontWeight(FontWeight.Bold)
//       }
//       .width('100%')
//     }
//     .height('100%')
//   }
// }