import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  communitySidebar: [{type: 'autogenerated', dirName: 'community'}],
  // tutorialSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: '第一季：基础入门',
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: true,
  //     items: [
  //       'session1/session-1-00',
  //       'session1/session-1-01',
  //       'session1/session-1-02',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '第二季：实战开发',
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: true,
  //     items: [
  //       'session2/session-2-00',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '第三季：HarmonyOS Next',
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: true,
  //     items: [
  //       'session3/session-3-00',
  //     ],
  //   },
  // ],
  // community: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'community',
  //   },
  //   // {
  //   //   type: 'link',
  //   //   href: '/showcase',
  //   //   label: 'Showcase',
  //   // },
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: '课程',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
